### ISSUE TITLE
Client-Filter wird nicht bei der Ts-List angewendet

### ISSUE THREAD

**Issue by RedstoneFuture** [RedstoneWorld/BungeeSpeak#3]
![grafik](https://user-images.githubusercontent.com/4140635/135699080-7d587625-47df-456a-9741-dcefc6b9d605.png)

Mit `/ts info` sehe ich anhand der angezeigten Client-Info, dass der aktivierte Filter angewendet wurde: es werden hier beide Musikbots abgezogen. Bei `/ts list` ist das nicht der Fall - da werden die 2 Musikbots mit angezeigt. Ich hab gerade selber schon im Code geschaut, konnte aber auf die Schnelle nicht den Fehler finden.

```
minecraft-commands:
  # Settings for filtering the client list
  filteredclientlist:

    # The rules with which we should filter, use empty list [] to not filter at all
    FilterRules:
    - "(.*)ILoveRadio(.*)"
    - "(.*)TechnoBase(.*)"

    # Enabled filtering in /ts info
    FilterInfo: true

    # Enable filterin in /ts list
    FilterList: true
```
